version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cd server && npm install
            - run: cd server && npm run lint
            - run: cd server && npm test
            - run: cd client && npm install
            - run: cd client && npm run lint
            - run: cd client && npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test